apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nicholasadamou/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-demo-app-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
