apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-per-app-set
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - environment: dev
          - environment: staging
          - environment: production
      - list:
          elements:
          - service: demo-app
          - service: api-service
  template:
    metadata:
      name: '{{environment}}-{{service}}'
      labels:
        environment: '{{environment}}'
        service: '{{service}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/nicholasadamou/argocd-app-config.git
        targetRevision: HEAD
        path: 'environments/{{environment}}/{{service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{environment}}-{{service}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
