apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  selector:
    matchLabels:
      app: argocd-demo-app
  replicas: 3  # More replicas for staging
  template:
    metadata:
      labels:
        app: argocd-demo-app
        environment: staging
    spec:
      containers:
      - name: argocd-demo-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: JAVA_OPTS
          value: "-Xmx300m -Xms150m -XX:+UseG1GC -XX:+UseContainerSupport"
        resources:
          requests:
            memory: "192Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "200m"
