apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nicholasadamou/argocd-app-config.git
    targetRevision: HEAD
    path: production
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-demo-app-production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: false  # More cautious for production
      prune: true
