apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  selector:
    matchLabels:
      app: api-service
  replicas: 3
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: "production"
