apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  selector:
    matchLabels:
      app: argocd-demo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: argocd-demo-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: JAVA_OPTS
          value: "-Xmx200m -Xms100m -XX:+UseG1GC -XX:+UseContainerSupport"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
